# Site settings
author: Skylor Rosario
title: Flatiron student Log .S
header-img: img/home-bg.png
email: skylora.rosario@gmail.com
copyright_name: Skylor Rosario
description: > # this means to ignore newlines until "baseurl:"
  S. log
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Skylor117

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
